warning_threshold: 15

excluded:
  - Pods
  - Frameworks

disabled_rules:
  - trailing_whitespace

line_length: 200

function_parameter_count:
  - warning: 10
  - error: 15

file_length:
  - warning: 500

type_body_length:
  - warning: 400
  - error: 450
