# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KidsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KidsApp

pod 'SnapKit', '~> 5.0.0'
pod 'CHIPageControl/Aleppo'

end
