# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'newMTB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for newMTB

pod 'SnapKit', '~> 5.0.0'
pod 'Alamofire', '~> 5.2'
pod 'GoogleMaps'
pod 'KeychainSwift'

end
